apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: like-service
build:
  artifacts:
  - image: docker.pkg.github.com/vinhut/like
deploy:
  helm:
    releases:
    - name: like-service
      chartPath: ../kube-deploy/charts/like-service
      valuesFiles: 
        - ../kube-deploy/charts/like-service/values.yaml
      values:
        imageName: docker.pkg.github.com/vinhut/like
